/** Graphics quality tiers — single source of truth for presets. */

export const QUALITY_LEVELS = ['low', 'medium', 'high', 'max'];

export function normalizeQuality(q) {
  return QUALITY_LEVELS.includes(q) ? q : 'medium';
}

/** @typedef {typeof QUALITY_TIERS.low} QualityTier */

export const QUALITY_TIERS = {
  low: {
    id: 'low',
    chunkSegs: 6,
    propCount: 0,
    loadRadius: 4,
    chunkBuildBudget: 8,
    waterSegs: 8,
    skySegs: [32, 20],
    meshClouds: false,
    meshCloudCount: 0,
    sunCore: 0,
    sunCorona: 0,
    sunCoronaTex: 0,
    sunSegs: 0,
    sunInnerMul: 0,
    sunOuterGlow: false,
    moonR: 8,
    moonSegs: [10, 8],
    terrainFlat: true,
    terrainRoughness: 0.94,
    terrainMetalness: 0,
    propsFlat: true,
    premium: false,
    shadows: false,
    shadowMapSize: 512,
    dprCap: 1,
    toneMapping: false,
    exposure: 1,
    hemiIntensity: 0.75,
    sunIntensity: 1.15,
    ambIntensity: 0.28,
    particleScale: 0.5,
    cloudPointSize: 10,
  },
  medium: {
    id: 'medium',
    chunkSegs: 8,
    propCount: 1,
    loadRadius: 5,
    chunkBuildBudget: 10,
    waterSegs: 12,
    skySegs: [40, 28],
    meshClouds: true,
    meshCloudCount: 10,
    sunCore: 12,
    sunCorona: 52,
    sunCoronaTex: 256,
    sunSegs: 8,
    sunInnerMul: 1.35,
    sunOuterGlow: false,
    moonR: 10,
    moonSegs: [14, 10],
    terrainFlat: true,
    terrainRoughness: 0.94,
    terrainMetalness: 0,
    propsFlat: true,
    premium: false,
    shadows: false,
    shadowMapSize: 512,
    dprCap: 1,
    toneMapping: false,
    exposure: 1,
    hemiIntensity: 0.75,
    sunIntensity: 1.15,
    ambIntensity: 0.28,
    particleScale: 1,
    cloudPointSize: 14,
  },
  high: {
    id: 'high',
    chunkSegs: 12,
    propCount: 2,
    loadRadius: 6,
    chunkBuildBudget: 14,
    waterSegs: 16,
    skySegs: [48, 32],
    meshClouds: true,
    meshCloudCount: 18,
    sunCore: 18,
    sunCorona: 72,
    sunCoronaTex: 384,
    sunSegs: 12,
    sunInnerMul: 1.45,
    sunOuterGlow: true,
    sunOuterMul: 2.1,
    moonR: 14,
    moonSegs: [14, 10],
    terrainFlat: true,
    terrainRoughness: 0.92,
    terrainMetalness: 0,
    propsFlat: true,
    premium: false,
    shadows: false,
    shadowMapSize: 512,
    dprCap: 1.25,
    toneMapping: false,
    exposure: 1,
    hemiIntensity: 0.78,
    sunIntensity: 1.2,
    ambIntensity: 0.3,
    particleScale: 1,
    cloudPointSize: 14,
  },
  max: {
    id: 'max',
    chunkSegs: 16,
    propCount: 4,
    loadRadius: 6,
    chunkBuildBudget: 20,
    waterSegs: 32,
    skySegs: [64, 48],
    meshClouds: true,
    meshCloudCount: 28,
    sunCore: 22,
    sunCorona: 88,
    sunCoronaTex: 512,
    sunSegs: 16,
    sunInnerMul: 1.55,
    sunOuterGlow: true,
    sunOuterMul: 2.4,
    moonR: 16,
    moonSegs: [20, 16],
    terrainFlat: false,
    terrainRoughness: 0.78,
    terrainMetalness: 0.04,
    propsFlat: false,
    premium: true,
    shadows: true,
    shadowMapSize: 1024,
    dprCap: 2,
    toneMapping: true,
    exposure: 1.18,
    hemiIntensity: 0.92,
    sunIntensity: 1.35,
    ambIntensity: 0.22,
    particleScale: 1.25,
    cloudPointSize: 18,
  },
};

export function getQualityTier(quality) {
  return QUALITY_TIERS[normalizeQuality(quality)] || QUALITY_TIERS.medium;
}
